// Generated by scripts/generate-lagoons-sl10-sl13-data.mjs from official DMT DCRs.

export type LagoonsDcrPhasePlot = {
  villaKey: string;
  dcrId: string;
  plotNumber: number;
  aldarPlotId: string;
  phase: "SL10" | "SL13";
  typology: string | null;
  landSqm: number;
  landSqft: number;
  maxGfaSqm: number | null;
  maxGfaSqft: number | null;
  latitude: number;
  longitude: number;
  boundary: { lat: number; lng: number }[];
  dcrUrl: string;
  dmtUrl: string;
  googleMapsUrl: string;
  coordinateSource: "official_dcr_centroid";
  availability: "unknown";
};

export const LAGOONS_SL10_PLOTS: LagoonsDcrPhasePlot[] = [
  {
    "villaKey": "lagoons-sl10/plot-1982",
    "dcrId": "SDE3_1982",
    "plotNumber": 1982,
    "aldarPlotId": "SL10-VI-021",
    "phase": "SL10",
    "typology": null,
    "landSqm": 1530.8,
    "landSqft": 16477.39,
    "maxGfaSqm": 1250,
    "maxGfaSqft": 13454.89,
    "latitude": 24.52907328,
    "longitude": 54.45922678,
    "boundary": [
      {
        "lat": 24.52921398,
        "lng": 54.45945503
      },
      {
        "lat": 24.52882888,
        "lng": 54.45930902
      },
      {
        "lat": 24.52892795,
        "lng": 54.45899682
      },
      {
        "lat": 24.52928434,
        "lng": 54.45913279
      },
      {
        "lat": 24.52930524,
        "lng": 54.45915041
      },
      {
        "lat": 24.52931057,
        "lng": 54.45918941
      }
    ],
    "dcrUrl": "/manus-storage/SDE3_1982_0abd3369.pdf",
    "dmtUrl": "https://geosmart.dmt.gov.ae/dcr/SDE3_1982.pdf",
    "googleMapsUrl": "https://www.google.com/maps?q=24.52907328,54.45922678",
    "coordinateSource": "official_dcr_centroid",
    "availability": "unknown"
  },
  {
    "villaKey": "lagoons-sl10/plot-1983",
    "dcrId": "SDE3_1983",
    "plotNumber": 1983,
    "aldarPlotId": "SL10-VI-022",
    "phase": "SL10",
    "typology": null,
    "landSqm": 1514.7,
    "landSqft": 16304.1,
    "maxGfaSqm": 1250,
    "maxGfaSqft": 13454.89,
    "latitude": 24.52897209,
    "longitude": 54.45953834,
    "boundary": [
      {
        "lat": 24.52912035,
        "lng": 54.45976931
      },
      {
        "lat": 24.52872981,
        "lng": 54.45962124
      },
      {
        "lat": 24.52882888,
        "lng": 54.45930902
      },
      {
        "lat": 24.52921398,
        "lng": 54.45945503
      },
      {
        "lat": 24.52912718,
        "lng": 54.45972903
      }
    ],
    "dcrUrl": "/manus-storage/SDE3_1983_64536bc3.pdf",
    "dmtUrl": "https://geosmart.dmt.gov.ae/dcr/SDE3_1983.pdf",
    "googleMapsUrl": "https://www.google.com/maps?q=24.52897209,54.45953834",
    "coordinateSource": "official_dcr_centroid",
    "availability": "unknown"
  },
  {
    "villaKey": "lagoons-sl10/plot-1984",
    "dcrId": "SDE3_1984",
    "plotNumber": 1984,
    "aldarPlotId": "SL10-VI-023",
    "phase": "SL10",
    "typology": null,
    "landSqm": 1654.6,
    "landSqft": 17809.97,
    "maxGfaSqm": 1250,
    "maxGfaSqft": 13454.89,
    "latitude": 24.52888432,
    "longitude": 54.45986313,
    "boundary": [
      {
        "lat": 24.52902706,
        "lng": 54.46013038
      },
      {
        "lat": 24.52862468,
        "lng": 54.4599059
      },
      {
        "lat": 24.52868058,
        "lng": 54.4597712
      },
      {
        "lat": 24.52872981,
        "lng": 54.45962124
      },
      {
        "lat": 24.52912035,
        "lng": 54.45976931
      },
      {
        "lat": 24.529088,
        "lng": 54.45992522
      }
    ],
    "dcrUrl": "/manus-storage/SDE3_1984_8b2b392f.pdf",
    "dmtUrl": "https://geosmart.dmt.gov.ae/dcr/SDE3_1984.pdf",
    "googleMapsUrl": "https://www.google.com/maps?q=24.52888432,54.45986313",
    "coordinateSource": "official_dcr_centroid",
    "availability": "unknown"
  },
  {
    "villaKey": "lagoons-sl10/plot-1985",
    "dcrId": "SDE3_1985",
    "plotNumber": 1985,
    "aldarPlotId": "SL10-VI-024",
    "phase": "SL10",
    "typology": null,
    "landSqm": 1765.7,
    "landSqft": 19005.84,
    "maxGfaSqm": 1250,
    "maxGfaSqft": 13454.89,
    "latitude": 24.52875807,
    "longitude": 54.46017109,
    "boundary": [
      {
        "lat": 24.52888652,
        "lng": 54.4604493
      },
      {
        "lat": 24.52847758,
        "lng": 54.46018141
      },
      {
        "lat": 24.52862468,
        "lng": 54.4599059
      },
      {
        "lat": 24.52902706,
        "lng": 54.46013038
      },
      {
        "lat": 24.52896245,
        "lng": 54.4602947
      }
    ],
    "dcrUrl": "/manus-storage/SDE3_1985_ed6e8fc6.pdf",
    "dmtUrl": "https://geosmart.dmt.gov.ae/dcr/SDE3_1985.pdf",
    "googleMapsUrl": "https://www.google.com/maps?q=24.52875807,54.46017109",
    "coordinateSource": "official_dcr_centroid",
    "availability": "unknown"
  },
  {
    "villaKey": "lagoons-sl10/plot-1986",
    "dcrId": "SDE3_1986",
    "plotNumber": 1986,
    "aldarPlotId": "SL10-VI-043",
    "phase": "SL10",
    "typology": null,
    "landSqm": 1615.6,
    "landSqft": 17390.17,
    "maxGfaSqm": 1250,
    "maxGfaSqft": 13454.89,
    "latitude": 24.52851419,
    "longitude": 54.46059408,
    "boundary": [
      {
        "lat": 24.52858681,
        "lng": 54.46086572
      },
      {
        "lat": 24.52824453,
        "lng": 54.46055399
      },
      {
        "lat": 24.52839732,
        "lng": 54.46032591
      },
      {
        "lat": 24.52879174,
        "lng": 54.46060801
      },
      {
        "lat": 24.52873837,
        "lng": 54.46068582
      },
      {
        "lat": 24.52869981,
        "lng": 54.46073743
      },
      {
        "lat": 24.52866838,
        "lng": 54.46077717
      },
      {
        "lat": 24.52862219,
        "lng": 54.46083183
      }
    ],
    "dcrUrl": "/manus-storage/SDE3_1986_c57c12b5.pdf",
    "dmtUrl": "https://geosmart.dmt.gov.ae/dcr/SDE3_1986.pdf",
    "googleMapsUrl": "https://www.google.com/maps?q=24.52851419,54.46059408",
    "coordinateSource": "official_dcr_centroid",
    "availability": "unknown"
  },
  {
    "villaKey": "lagoons-sl10/plot-1987",
    "dcrId": "SDE3_1987",
    "plotNumber": 1987,
    "aldarPlotId": "SL10-VI-044",
    "phase": "SL10",
    "typology": null,
    "landSqm": 1578.8,
    "landSqft": 16994.06,
    "maxGfaSqm": 1250,
    "maxGfaSqft": 13454.89,
    "latitude": 24.52831207,
    "longitude": 54.46082732,
    "boundary": [
      {
        "lat": 24.52833783,
        "lng": 54.46110416
      },
      {
        "lat": 24.52805644,
        "lng": 54.46077001
      },
      {
        "lat": 24.52824453,
        "lng": 54.46055399
      },
      {
        "lat": 24.52858681,
        "lng": 54.46086572
      }
    ],
    "dcrUrl": "/manus-storage/SDE3_1987_d7db00dc.pdf",
    "dmtUrl": "https://geosmart.dmt.gov.ae/dcr/SDE3_1987.pdf",
    "googleMapsUrl": "https://www.google.com/maps?q=24.52831207,54.46082732",
    "coordinateSource": "official_dcr_centroid",
    "availability": "unknown"
  },
  {
    "villaKey": "lagoons-sl10/plot-1988",
    "dcrId": "SDE3_1988",
    "plotNumber": 1988,
    "aldarPlotId": "SL10-VI-045",
    "phase": "SL10",
    "typology": null,
    "landSqm": 1546,
    "landSqft": 16641.01,
    "maxGfaSqm": 1250,
    "maxGfaSqft": 13454.89,
    "latitude": 24.52808575,
    "longitude": 54.46104914,
    "boundary": [
      {
        "lat": 24.52809048,
        "lng": 54.46134106
      },
      {
        "lat": 24.52784395,
        "lng": 54.46095706
      },
      {
        "lat": 24.52805644,
        "lng": 54.46077001
      },
      {
        "lat": 24.52833783,
        "lng": 54.46110416
      }
    ],
    "dcrUrl": "/manus-storage/SDE3_1988_97520589.pdf",
    "dmtUrl": "https://geosmart.dmt.gov.ae/dcr/SDE3_1988.pdf",
    "googleMapsUrl": "https://www.google.com/maps?q=24.52808575,54.46104914",
    "coordinateSource": "official_dcr_centroid",
    "availability": "unknown"
  },
  {
    "villaKey": "lagoons-sl10/plot-1989",
    "dcrId": "SDE3_1989",
    "plotNumber": 1989,
    "aldarPlotId": "SL10-VI-046",
    "phase": "SL10",
    "typology": null,
    "landSqm": 1629.1,
    "landSqft": 17535.49,
    "maxGfaSqm": 1250,
    "maxGfaSqft": 13454.89,
    "latitude": 24.52784604,
    "longitude": 54.46124755,
    "boundary": [
      {
        "lat": 24.527806,
        "lng": 54.461522
      },
      {
        "lat": 24.52761078,
        "lng": 54.46111187
      },
      {
        "lat": 24.52784395,
        "lng": 54.46095706
      },
      {
        "lat": 24.52809048,
        "lng": 54.46134106
      },
      {
        "lat": 24.52795723,
        "lng": 54.46146868
      }
    ],
    "dcrUrl": "/manus-storage/SDE3_1989_9b411cbf.pdf",
    "dmtUrl": "https://geosmart.dmt.gov.ae/dcr/SDE3_1989.pdf",
    "googleMapsUrl": "https://www.google.com/maps?q=24.52784604,54.46124755",
    "coordinateSource": "official_dcr_centroid",
    "availability": "unknown"
  },
  {
    "villaKey": "lagoons-sl10/plot-1990",
    "dcrId": "SDE3_1990",
    "plotNumber": 1990,
    "aldarPlotId": "SL10-VI-047",
    "phase": "SL10",
    "typology": null,
    "landSqm": 1510.1,
    "landSqft": 16254.58,
    "maxGfaSqm": 1250,
    "maxGfaSqft": 13454.89,
    "latitude": 24.52756865,
    "longitude": 54.461379,
    "boundary": [
      {
        "lat": 24.52750408,
        "lng": 54.46163483
      },
      {
        "lat": 24.52734192,
        "lng": 54.46123934
      },
      {
        "lat": 24.52748841,
        "lng": 54.46117599
      },
      {
        "lat": 24.52761078,
        "lng": 54.46111187
      },
      {
        "lat": 24.527806,
        "lng": 54.461522
      },
      {
        "lat": 24.52761383,
        "lng": 54.46158892
      },
      {
        "lat": 24.52756124,
        "lng": 54.46160896
      }
    ],
    "dcrUrl": "/manus-storage/SDE3_1990_3f8d48e9.pdf",
    "dmtUrl": "https://geosmart.dmt.gov.ae/dcr/SDE3_1990.pdf",
    "googleMapsUrl": "https://www.google.com/maps?q=24.52756865,54.46137900",
    "coordinateSource": "official_dcr_centroid",
    "availability": "unknown"
  },
  {
    "villaKey": "lagoons-sl10/plot-1991",
    "dcrId": "SDE3_1991",
    "plotNumber": 1991,
    "aldarPlotId": "SL10-VI-048",
    "phase": "SL10",
    "typology": null,
    "landSqm": 1580.9,
    "landSqft": 17016.67,
    "maxGfaSqm": 1250,
    "maxGfaSqft": 13454.89,
    "latitude": 24.52727296,
    "longitude": 54.46149915,
    "boundary": [
      {
        "lat": 24.52723815,
        "lng": 54.46176503
      },
      {
        "lat": 24.52702766,
        "lng": 54.46139661
      },
      {
        "lat": 24.52714162,
        "lng": 54.46131887
      },
      {
        "lat": 24.52734192,
        "lng": 54.46123934
      },
      {
        "lat": 24.52750408,
        "lng": 54.46163483
      }
    ],
    "dcrUrl": "/manus-storage/SDE3_1991_0472b58e.pdf",
    "dmtUrl": "https://geosmart.dmt.gov.ae/dcr/SDE3_1991.pdf",
    "googleMapsUrl": "https://www.google.com/maps?q=24.52727296,54.46149915",
    "coordinateSource": "official_dcr_centroid",
    "availability": "unknown"
  },
  {
    "villaKey": "lagoons-sl10/plot-1992",
    "dcrId": "SDE3_1992",
    "plotNumber": 1992,
    "aldarPlotId": "SL10-VI-049",
    "phase": "SL10",
    "typology": null,
    "landSqm": 1526.6,
    "landSqft": 16432.19,
    "maxGfaSqm": 1250,
    "maxGfaSqft": 13454.89,
    "latitude": 24.52699738,
    "longitude": 54.46167102,
    "boundary": [
      {
        "lat": 24.52696726,
        "lng": 54.46194808
      },
      {
        "lat": 24.52675971,
        "lng": 54.46157939
      },
      {
        "lat": 24.52702766,
        "lng": 54.46139661
      },
      {
        "lat": 24.52723815,
        "lng": 54.46176503
      },
      {
        "lat": 24.52711987,
        "lng": 54.46183674
      }
    ],
    "dcrUrl": "/manus-storage/SDE3_1992_037a482a.pdf",
    "dmtUrl": "https://geosmart.dmt.gov.ae/dcr/SDE3_1992.pdf",
    "googleMapsUrl": "https://www.google.com/maps?q=24.52699738,54.46167102",
    "coordinateSource": "official_dcr_centroid",
    "availability": "unknown"
  },
  {
    "villaKey": "lagoons-sl10/plot-1993",
    "dcrId": "SDE3_1993",
    "plotNumber": 1993,
    "aldarPlotId": "SL10-VI-050",
    "phase": "SL10",
    "typology": null,
    "landSqm": 1593.4,
    "landSqft": 17151.21,
    "maxGfaSqm": 1250,
    "maxGfaSqft": 13454.89,
    "latitude": 24.52669556,
    "longitude": 54.4618893,
    "boundary": [
      {
        "lat": 24.52667945,
        "lng": 54.46218388
      },
      {
        "lat": 24.52666234,
        "lng": 54.46215414
      },
      {
        "lat": 24.52645347,
        "lng": 54.46178828
      },
      {
        "lat": 24.52672142,
        "lng": 54.4616055
      },
      {
        "lat": 24.52693225,
        "lng": 54.4619749
      }
    ],
    "dcrUrl": "/manus-storage/SDE3_1993_7bd6278a.pdf",
    "dmtUrl": "https://geosmart.dmt.gov.ae/dcr/SDE3_1993.pdf",
    "googleMapsUrl": "https://www.google.com/maps?q=24.52669556,54.46188930",
    "coordinateSource": "official_dcr_centroid",
    "availability": "unknown"
  },
  {
    "villaKey": "lagoons-sl10/plot-1994",
    "dcrId": "SDE3_1994",
    "plotNumber": 1994,
    "aldarPlotId": "SL10-VI-051",
    "phase": "SL10",
    "typology": null,
    "landSqm": 1503.6,
    "landSqft": 16184.62,
    "maxGfaSqm": 1250,
    "maxGfaSqft": 13454.89,
    "latitude": 24.52642717,
    "longitude": 54.4620617,
    "boundary": [
      {
        "lat": 24.52640287,
        "lng": 54.46233688
      },
      {
        "lat": 24.52619164,
        "lng": 54.46196688
      },
      {
        "lat": 24.52645347,
        "lng": 54.46178828
      },
      {
        "lat": 24.52666234,
        "lng": 54.46215414
      },
      {
        "lat": 24.52658808,
        "lng": 54.46220643
      }
    ],
    "dcrUrl": "/manus-storage/SDE3_1994_1bd4dc50.pdf",
    "dmtUrl": "https://geosmart.dmt.gov.ae/dcr/SDE3_1994.pdf",
    "googleMapsUrl": "https://www.google.com/maps?q=24.52642717,54.46206170",
    "coordinateSource": "official_dcr_centroid",
    "availability": "unknown"
  },
  {
    "villaKey": "lagoons-sl10/plot-1995",
    "dcrId": "SDE3_1995",
    "plotNumber": 1995,
    "aldarPlotId": "SL10-VI-052",
    "phase": "SL10",
    "typology": null,
    "landSqm": 1501.6,
    "landSqft": 16163.09,
    "maxGfaSqm": 1250,
    "maxGfaSqft": 13454.89,
    "latitude": 24.52616857,
    "longitude": 54.46224141,
    "boundary": [
      {
        "lat": 24.52640287,
        "lng": 54.46233688
      },
      {
        "lat": 24.52614644,
        "lng": 54.4625175
      },
      {
        "lat": 24.52594003,
        "lng": 54.46215595
      },
      {
        "lat": 24.52594435,
        "lng": 54.46213556
      },
      {
        "lat": 24.52619164,
        "lng": 54.46196688
      }
    ],
    "dcrUrl": "/manus-storage/SDE3_1995_3000a406.pdf",
    "dmtUrl": "https://geosmart.dmt.gov.ae/dcr/SDE3_1995.pdf",
    "googleMapsUrl": "https://www.google.com/maps?q=24.52616857,54.46224141",
    "coordinateSource": "official_dcr_centroid",
    "availability": "unknown"
  },
  {
    "villaKey": "lagoons-sl10/plot-1996",
    "dcrId": "SDE3_1996",
    "plotNumber": 1996,
    "aldarPlotId": "SL10-VI-035",
    "phase": "SL10",
    "typology": null,
    "landSqm": 1501.4,
    "landSqft": 16160.94,
    "maxGfaSqm": 1250,
    "maxGfaSqft": 13454.89,
    "latitude": 24.52581435,
    "longitude": 54.46165945,
    "boundary": [
      {
        "lat": 24.52582013,
        "lng": 54.46191798
      },
      {
        "lat": 24.52577661,
        "lng": 54.46190696
      },
      {
        "lat": 24.52557835,
        "lng": 54.46155968
      },
      {
        "lat": 24.52583482,
        "lng": 54.46138472
      },
      {
        "lat": 24.52604981,
        "lng": 54.46176131
      }
    ],
    "dcrUrl": "/manus-storage/SDE3_1996_639856c6.pdf",
    "dmtUrl": "https://geosmart.dmt.gov.ae/dcr/SDE3_1996.pdf",
    "googleMapsUrl": "https://www.google.com/maps?q=24.52581435,54.46165945",
    "coordinateSource": "official_dcr_centroid",
    "availability": "unknown"
  },
  {
    "villaKey": "lagoons-sl10/plot-1997",
    "dcrId": "SDE3_1997",
    "plotNumber": 1997,
    "aldarPlotId": "SL10-VI-034",
    "phase": "SL10",
    "typology": null,
    "landSqm": 1501.4,
    "landSqft": 16160.94,
    "maxGfaSqm": 1250,
    "maxGfaSqft": 13454.89,
    "latitude": 24.52560012,
    "longitude": 54.46128432,
    "boundary": [
      {
        "lat": 24.52583482,
        "lng": 54.46138472
      },
      {
        "lat": 24.52557835,
        "lng": 54.46155968
      },
      {
        "lat": 24.52538008,
        "lng": 54.46121238
      },
      {
        "lat": 24.52539015,
        "lng": 54.46116481
      },
      {
        "lat": 24.52561983,
        "lng": 54.46100815
      }
    ],
    "dcrUrl": "/manus-storage/SDE3_1997_2e7b159e.pdf",
    "dmtUrl": "https://geosmart.dmt.gov.ae/dcr/SDE3_1997.pdf",
    "googleMapsUrl": "https://www.google.com/maps?q=24.52560012,54.46128432",
    "coordinateSource": "official_dcr_centroid",
    "availability": "unknown"
  },
  {
    "villaKey": "lagoons-sl10/plot-1998",
    "dcrId": "SDE3_1998",
    "plotNumber": 1998,
    "aldarPlotId": "SL10-VI-036",
    "phase": "SL10",
    "typology": null,
    "landSqm": 1507.5,
    "landSqft": 16226.59,
    "maxGfaSqm": 1250,
    "maxGfaSqft": 13454.89,
    "latitude": 24.5260699,
    "longitude": 54.46148549,
    "boundary": [
      {
        "lat": 24.52604981,
        "lng": 54.46176131
      },
      {
        "lat": 24.52583482,
        "lng": 54.46138472
      },
      {
        "lat": 24.5260913,
        "lng": 54.46120978
      },
      {
        "lat": 24.52630629,
        "lng": 54.46158636
      }
    ],
    "dcrUrl": "/manus-storage/SDE3_1998_749cddf5.pdf",
    "dmtUrl": "https://geosmart.dmt.gov.ae/dcr/SDE3_1998.pdf",
    "googleMapsUrl": "https://www.google.com/maps?q=24.52606990,54.46148549",
    "coordinateSource": "official_dcr_centroid",
    "availability": "unknown"
  },
  {
    "villaKey": "lagoons-sl10/plot-1999",
    "dcrId": "SDE3_1999",
    "plotNumber": 1999,
    "aldarPlotId": "SL10-VI-033",
    "phase": "SL10",
    "typology": null,
    "landSqm": 1507.5,
    "landSqft": 16226.59,
    "maxGfaSqm": 1250,
    "maxGfaSqft": 13454.89,
    "latitude": 24.52585596,
    "longitude": 54.46110899,
    "boundary": [
      {
        "lat": 24.5260913,
        "lng": 54.46120978
      },
      {
        "lat": 24.52583482,
        "lng": 54.46138472
      },
      {
        "lat": 24.52561983,
        "lng": 54.46100815
      },
      {
        "lat": 24.5258763,
        "lng": 54.4608332
      }
    ],
    "dcrUrl": "/manus-storage/SDE3_1999_6c3e9dae.pdf",
    "dmtUrl": "https://geosmart.dmt.gov.ae/dcr/SDE3_1999.pdf",
    "googleMapsUrl": "https://www.google.com/maps?q=24.52585596,54.46110899",
    "coordinateSource": "official_dcr_centroid",
    "availability": "unknown"
  }
];

export const LAGOONS_SL13_PLOTS: LagoonsDcrPhasePlot[] = [
  {
    "villaKey": "lagoons-sl13/plot-1966",
    "dcrId": "SDE3_1966",
    "plotNumber": 1966,
    "aldarPlotId": "SL13-VI-016",
    "phase": "SL13",
    "typology": null,
    "landSqm": 2787.7,
    "landSqft": 30006.55,
    "maxGfaSqm": 2500,
    "maxGfaSqft": 26909.78,
    "latitude": 24.53930136,
    "longitude": 54.45884472,
    "boundary": [
      {
        "lat": 24.53920315,
        "lng": 54.45917926
      },
      {
        "lat": 24.53901512,
        "lng": 54.45860999
      },
      {
        "lat": 24.53933656,
        "lng": 54.45848767
      },
      {
        "lat": 24.53939463,
        "lng": 54.45851778
      },
      {
        "lat": 24.53946005,
        "lng": 54.45871379
      },
      {
        "lat": 24.53959151,
        "lng": 54.45910777
      },
      {
        "lat": 24.53955239,
        "lng": 54.45912263
      }
    ],
    "dcrUrl": "/manus-storage/SDE3_1966_f02cef3e.pdf",
    "dmtUrl": "https://geosmart.dmt.gov.ae/dcr/SDE3_1966.pdf",
    "googleMapsUrl": "https://www.google.com/maps?q=24.53930136,54.45884472",
    "coordinateSource": "official_dcr_centroid",
    "availability": "unknown"
  },
  {
    "villaKey": "lagoons-sl13/plot-1967",
    "dcrId": "SDE3_1967",
    "plotNumber": 1967,
    "aldarPlotId": "SL13-VI-015",
    "phase": "SL13",
    "typology": null,
    "landSqm": 2823.9,
    "landSqft": 30396.21,
    "maxGfaSqm": 2500,
    "maxGfaSqft": 26909.78,
    "latitude": 24.53887163,
    "longitude": 54.45902366,
    "boundary": [
      {
        "lat": 24.53854616,
        "lng": 54.45932432
      },
      {
        "lat": 24.53849416,
        "lng": 54.45914429
      },
      {
        "lat": 24.538537,
        "lng": 54.45911837
      },
      {
        "lat": 24.5386602,
        "lng": 54.45898903
      },
      {
        "lat": 24.53897273,
        "lng": 54.4586269
      },
      {
        "lat": 24.53901512,
        "lng": 54.45860999
      },
      {
        "lat": 24.53920315,
        "lng": 54.45917926
      },
      {
        "lat": 24.53875998,
        "lng": 54.45925114
      }
    ],
    "dcrUrl": "/manus-storage/SDE3_1967_0687bb41.pdf",
    "dmtUrl": "https://geosmart.dmt.gov.ae/dcr/SDE3_1967.pdf",
    "googleMapsUrl": "https://www.google.com/maps?q=24.53887163,54.45902366",
    "coordinateSource": "official_dcr_centroid",
    "availability": "unknown"
  },
  {
    "villaKey": "lagoons-sl13/plot-1970",
    "dcrId": "SDE3_1970",
    "plotNumber": 1970,
    "aldarPlotId": "SL13-VI-012",
    "phase": "SL13",
    "typology": null,
    "landSqm": 3859.1,
    "landSqft": 41539.01,
    "maxGfaSqm": 2500,
    "maxGfaSqft": 26909.78,
    "latitude": 24.53601348,
    "longitude": 54.45959608,
    "boundary": [
      {
        "lat": 24.53607673,
        "lng": 54.46027767
      },
      {
        "lat": 24.53583031,
        "lng": 54.45996214
      },
      {
        "lat": 24.53582675,
        "lng": 54.45977118
      },
      {
        "lat": 24.53587049,
        "lng": 54.45906076
      },
      {
        "lat": 24.53594726,
        "lng": 54.45907377
      },
      {
        "lat": 24.53604926,
        "lng": 54.4591053
      },
      {
        "lat": 24.5362486,
        "lng": 54.45920257
      }
    ],
    "dcrUrl": "/manus-storage/SDE3_1970_b5b47d94.pdf",
    "dmtUrl": "https://geosmart.dmt.gov.ae/dcr/SDE3_1970.pdf",
    "googleMapsUrl": "https://www.google.com/maps?q=24.53601348,54.45959608",
    "coordinateSource": "official_dcr_centroid",
    "availability": "unknown"
  },
  {
    "villaKey": "lagoons-sl13/plot-1971",
    "dcrId": "SDE3_1971",
    "plotNumber": 1971,
    "aldarPlotId": "SL13-VI-001",
    "phase": "SL13",
    "typology": null,
    "landSqm": 4783.7,
    "landSqft": 51491.32,
    "maxGfaSqm": 2500,
    "maxGfaSqft": 26909.78,
    "latitude": 24.53570878,
    "longitude": 54.45855987,
    "boundary": [
      {
        "lat": 24.53593012,
        "lng": 54.45890834
      },
      {
        "lat": 24.53572781,
        "lng": 54.45886091
      },
      {
        "lat": 24.5356553,
        "lng": 54.45867624
      },
      {
        "lat": 24.53563867,
        "lng": 54.45861175
      },
      {
        "lat": 24.53564658,
        "lng": 54.45858638
      },
      {
        "lat": 24.5356429,
        "lng": 54.45836861
      },
      {
        "lat": 24.53549327,
        "lng": 54.45808207
      },
      {
        "lat": 24.53546907,
        "lng": 54.45796503
      },
      {
        "lat": 24.53547743,
        "lng": 54.45791994
      }
    ],
    "dcrUrl": "/manus-storage/SDE3_1971_4eef2f82.pdf",
    "dmtUrl": "https://geosmart.dmt.gov.ae/dcr/SDE3_1971.pdf",
    "googleMapsUrl": "https://www.google.com/maps?q=24.53570878,54.45855987",
    "coordinateSource": "official_dcr_centroid",
    "availability": "unknown"
  },
  {
    "villaKey": "lagoons-sl13/plot-1972",
    "dcrId": "SDE3_1972",
    "plotNumber": 1972,
    "aldarPlotId": "SL13-VI-002",
    "phase": "SL13",
    "typology": null,
    "landSqm": 3488.8,
    "landSqft": 37553.13,
    "maxGfaSqm": 2500,
    "maxGfaSqft": 26909.78,
    "latitude": 24.53539735,
    "longitude": 54.45679287,
    "boundary": [
      {
        "lat": 24.53503475,
        "lng": 54.45655963
      },
      {
        "lat": 24.53533639,
        "lng": 54.45632823
      },
      {
        "lat": 24.53564509,
        "lng": 54.45680704
      },
      {
        "lat": 24.5356992,
        "lng": 54.45703051
      },
      {
        "lat": 24.53562597,
        "lng": 54.45719374
      },
      {
        "lat": 24.53557991,
        "lng": 54.45726951
      },
      {
        "lat": 24.53552958,
        "lng": 54.45718763
      },
      {
        "lat": 24.53545468,
        "lng": 54.45724265
      }
    ],
    "dcrUrl": "/manus-storage/SDE3_1972_9308caf1.pdf",
    "dmtUrl": "https://geosmart.dmt.gov.ae/dcr/SDE3_1972.pdf",
    "googleMapsUrl": "https://www.google.com/maps?q=24.53539735,54.45679287",
    "coordinateSource": "official_dcr_centroid",
    "availability": "unknown"
  },
  {
    "villaKey": "lagoons-sl13/plot-1973",
    "dcrId": "SDE3_1973",
    "plotNumber": 1973,
    "aldarPlotId": "SL13-VI-003",
    "phase": "SL13",
    "typology": null,
    "landSqm": 3375.5,
    "landSqft": 36333.58,
    "maxGfaSqm": 2500,
    "maxGfaSqft": 26909.78,
    "latitude": 24.53495811,
    "longitude": 54.45610511,
    "boundary": [
      {
        "lat": 24.53476217,
        "lng": 54.45611629
      },
      {
        "lat": 24.53454404,
        "lng": 54.4557615
      },
      {
        "lat": 24.53468083,
        "lng": 54.4557302
      },
      {
        "lat": 24.53488986,
        "lng": 54.45575464
      },
      {
        "lat": 24.53503914,
        "lng": 54.45586715
      },
      {
        "lat": 24.53533639,
        "lng": 54.45632823
      },
      {
        "lat": 24.53503475,
        "lng": 54.45655963
      }
    ],
    "dcrUrl": "/manus-storage/SDE3_1973_4af52f0c.pdf",
    "dmtUrl": "https://geosmart.dmt.gov.ae/dcr/SDE3_1973.pdf",
    "googleMapsUrl": "https://www.google.com/maps?q=24.53495811,54.45610511",
    "coordinateSource": "official_dcr_centroid",
    "availability": "unknown"
  },
  {
    "villaKey": "lagoons-sl13/plot-1974",
    "dcrId": "SDE3_1974",
    "plotNumber": 1974,
    "aldarPlotId": "SL13-VI-004",
    "phase": "SL13",
    "typology": null,
    "landSqm": 4283.4,
    "landSqft": 46106.13,
    "maxGfaSqm": 2500,
    "maxGfaSqft": 26909.78,
    "latitude": 24.5343043,
    "longitude": 54.45619411,
    "boundary": [
      {
        "lat": 24.53399743,
        "lng": 54.45667815
      },
      {
        "lat": 24.53391083,
        "lng": 54.45653813
      },
      {
        "lat": 24.53397908,
        "lng": 54.45618215
      },
      {
        "lat": 24.53440642,
        "lng": 54.45579298
      },
      {
        "lat": 24.53454404,
        "lng": 54.4557615
      },
      {
        "lat": 24.53476217,
        "lng": 54.45611629
      },
      {
        "lat": 24.53453748,
        "lng": 54.45628137
      }
    ],
    "dcrUrl": "/manus-storage/SDE3_1974_5bc5a581.pdf",
    "dmtUrl": "https://geosmart.dmt.gov.ae/dcr/SDE3_1974.pdf",
    "googleMapsUrl": "https://www.google.com/maps?q=24.53430430,54.45619411",
    "coordinateSource": "official_dcr_centroid",
    "availability": "unknown"
  },
  {
    "villaKey": "lagoons-sl13/plot-1975",
    "dcrId": "SDE3_1975",
    "plotNumber": 1975,
    "aldarPlotId": "SL13-VI-005",
    "phase": "SL13",
    "typology": null,
    "landSqm": 3266.5,
    "landSqft": 35160.31,
    "maxGfaSqm": 2500,
    "maxGfaSqft": 26909.78,
    "latitude": 24.5343944,
    "longitude": 54.45665867,
    "boundary": [
      {
        "lat": 24.53415297,
        "lng": 54.45692961
      },
      {
        "lat": 24.53399743,
        "lng": 54.45667815
      },
      {
        "lat": 24.53453748,
        "lng": 54.45628137
      },
      {
        "lat": 24.53477761,
        "lng": 54.45667195
      },
      {
        "lat": 24.53437693,
        "lng": 54.45696634
      },
      {
        "lat": 24.5343622,
        "lng": 54.45695316
      }
    ],
    "dcrUrl": "/manus-storage/SDE3_1975_101b5b93.pdf",
    "dmtUrl": "https://geosmart.dmt.gov.ae/dcr/SDE3_1975.pdf",
    "googleMapsUrl": "https://www.google.com/maps?q=24.53439440,54.45665867",
    "coordinateSource": "official_dcr_centroid",
    "availability": "unknown"
  },
  {
    "villaKey": "lagoons-sl13/plot-1978",
    "dcrId": "SDE3_1978",
    "plotNumber": 1978,
    "aldarPlotId": "SL13-VI-011",
    "phase": "SL13",
    "typology": null,
    "landSqm": 4494.8,
    "landSqft": 48381.62,
    "maxGfaSqm": 2500,
    "maxGfaSqft": 26909.78,
    "latitude": 24.53338261,
    "longitude": 54.45890852,
    "boundary": [
      {
        "lat": 24.53386853,
        "lng": 54.45873738
      },
      {
        "lat": 24.53384899,
        "lng": 54.45892317
      },
      {
        "lat": 24.53384879,
        "lng": 54.45892314
      },
      {
        "lat": 24.5337289,
        "lng": 54.45902183
      },
      {
        "lat": 24.53353494,
        "lng": 54.45904756
      },
      {
        "lat": 24.53327011,
        "lng": 54.45915198
      },
      {
        "lat": 24.53311057,
        "lng": 54.45929541
      },
      {
        "lat": 24.53292765,
        "lng": 54.45891495
      },
      {
        "lat": 24.53332216,
        "lng": 54.4586248
      }
    ],
    "dcrUrl": "/manus-storage/SDE3_1978_43c2bce0.pdf",
    "dmtUrl": "https://geosmart.dmt.gov.ae/dcr/SDE3_1978.pdf",
    "googleMapsUrl": "https://www.google.com/maps?q=24.53338261,54.45890852",
    "coordinateSource": "official_dcr_centroid",
    "availability": "unknown"
  },
  {
    "villaKey": "lagoons-sl13/plot-1979",
    "dcrId": "SDE3_1979",
    "plotNumber": 1979,
    "aldarPlotId": "SL13-VI-010",
    "phase": "SL13",
    "typology": null,
    "landSqm": 5567.9,
    "landSqft": 59932.38,
    "maxGfaSqm": 2500,
    "maxGfaSqft": 26909.78,
    "latitude": 24.53270697,
    "longitude": 54.45927653,
    "boundary": [
      {
        "lat": 24.53265311,
        "lng": 54.45992932
      },
      {
        "lat": 24.53249008,
        "lng": 54.45989324
      },
      {
        "lat": 24.53249278,
        "lng": 54.45956983
      },
      {
        "lat": 24.53238351,
        "lng": 54.45896807
      },
      {
        "lat": 24.53283269,
        "lng": 54.45871744
      },
      {
        "lat": 24.53292765,
        "lng": 54.45891495
      },
      {
        "lat": 24.53311057,
        "lng": 54.45929541
      },
      {
        "lat": 24.53301958,
        "lng": 54.4593772
      },
      {
        "lat": 24.53272647,
        "lng": 54.45971406
      }
    ],
    "dcrUrl": "/manus-storage/SDE3_1979_c949d991.pdf",
    "dmtUrl": "https://geosmart.dmt.gov.ae/dcr/SDE3_1979.pdf",
    "googleMapsUrl": "https://www.google.com/maps?q=24.53270697,54.45927653",
    "coordinateSource": "official_dcr_centroid",
    "availability": "unknown"
  },
  {
    "villaKey": "lagoons-sl13/plot-1980",
    "dcrId": "SDE3_1980",
    "plotNumber": 1980,
    "aldarPlotId": "SL13-VI-009",
    "phase": "SL13",
    "typology": null,
    "landSqm": 4867.5,
    "landSqft": 52393.33,
    "maxGfaSqm": 2500,
    "maxGfaSqft": 26909.78,
    "latitude": 24.53245573,
    "longitude": 54.45865098,
    "boundary": [
      {
        "lat": 24.53283269,
        "lng": 54.45871744
      },
      {
        "lat": 24.53238351,
        "lng": 54.45896807
      },
      {
        "lat": 24.5323774,
        "lng": 54.4589344
      },
      {
        "lat": 24.53229683,
        "lng": 54.45875754
      },
      {
        "lat": 24.53222381,
        "lng": 54.45861005
      },
      {
        "lat": 24.5322056,
        "lng": 54.45855341
      },
      {
        "lat": 24.53222999,
        "lng": 54.45839888
      },
      {
        "lat": 24.53224408,
        "lng": 54.45835512
      },
      {
        "lat": 24.5322591,
        "lng": 54.45830289
      }
    ],
    "dcrUrl": "/manus-storage/SDE3_1980_c9ab140f.pdf",
    "dmtUrl": "https://geosmart.dmt.gov.ae/dcr/SDE3_1980.pdf",
    "googleMapsUrl": "https://www.google.com/maps?q=24.53245573,54.45865098",
    "coordinateSource": "official_dcr_centroid",
    "availability": "unknown"
  },
  {
    "villaKey": "lagoons-sl13/plot-1981",
    "dcrId": "SDE3_1981",
    "plotNumber": 1981,
    "aldarPlotId": "SL13-VI-008",
    "phase": "SL13",
    "typology": null,
    "landSqm": 3387.8,
    "landSqft": 36465.98,
    "maxGfaSqm": 2500,
    "maxGfaSqft": 26909.78,
    "latitude": 24.53298934,
    "longitude": 54.45817436,
    "boundary": [
      {
        "lat": 24.53347253,
        "lng": 54.45840049
      },
      {
        "lat": 24.53314271,
        "lng": 54.45837258
      },
      {
        "lat": 24.53308231,
        "lng": 54.4583739
      },
      {
        "lat": 24.53299412,
        "lng": 54.45839604
      },
      {
        "lat": 24.53283495,
        "lng": 54.45847303
      },
      {
        "lat": 24.53259863,
        "lng": 54.45797217
      },
      {
        "lat": 24.53264977,
        "lng": 54.4579675
      },
      {
        "lat": 24.53290048,
        "lng": 54.45790517
      },
      {
        "lat": 24.53305834,
        "lng": 54.45789391
      }
    ],
    "dcrUrl": "/manus-storage/SDE3_1981_3847a604.pdf",
    "dmtUrl": "https://geosmart.dmt.gov.ae/dcr/SDE3_1981.pdf",
    "googleMapsUrl": "https://www.google.com/maps?q=24.53298934,54.45817436",
    "coordinateSource": "official_dcr_centroid",
    "availability": "unknown"
  }
];

export const LAGOONS_DCR_PHASE_SUMMARIES = {
  SL10: { projectName: "Saadiyat Lagoons · Hidden Phase SL10", phase: "SL10", sourceRange: "SDE3_1982–SDE3_1999", officialPlotCount: LAGOONS_SL10_PLOTS.length },
  SL13: { projectName: "Saadiyat Lagoons · Phase SL13", phase: "SL13", sourceRange: "SDE3_1966–SDE3_1981", officialPlotCount: LAGOONS_SL13_PLOTS.length },
} as const;
