"""Enrich calibrated Lagoons coordinates with documented card fields for map popups.

Run after calibrate-lagoons-from-controls.py. It preserves every coordinate and
position source, then joins the authoritative Aldar unit record and direct user
controls to add prices, areas, specifications, and a DCR link where registered.
"""

from __future__ import annotations

import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
COORDINATES = ROOT / "client/src/data/lagoonsCoordinates.ts"
SOURCE = ROOT / "server/data/lagoons.json"
CONTROLS = ROOT / "scripts/source-data/lagoons-controls.json"


def main() -> None:
    source = json.loads(SOURCE.read_text(encoding="utf-8"))
    source_by_name = {villa["unit_name"]: villa for villa in source["villas"]}
    controls = json.loads(CONTROLS.read_text(encoding="utf-8")).get("controls", [])
    controls_by_name = {
        control["unitName"]: control
        for control in controls
        if control.get("unitName") and control.get("sdn3PlotNumber")
    }

    previous = COORDINATES.read_text(encoding="utf-8")
    match = re.search(r"= (\[.*\]);\s*$", previous, flags=re.DOTALL)
    if match is None:
        raise RuntimeError("Could not parse lagoonsVillaCoords array")
    rows = json.loads(match.group(1))

    for row in rows:
        villa = source_by_name.get(row["unit_name"])
        if villa is None:
            raise RuntimeError(f"Missing source record for {row['unit_name']}")
        aldar = villa.get("aldar_data") or {}
        control = controls_by_name.get(row["unit_name"])
        row.update({
            "saleable_area_sqm": villa.get("saleable_area_sqm") or 0,
            "total_area_sqm": aldar.get("total_area_sqm") or 0,
            "original_price_aed": aldar.get("selling_price_aed") or 0,
            "unit_type": villa.get("type") or "",
            "model": villa.get("model") or "",
            "dcr_url": f"https://geosmart.dmt.gov.ae/dcr/SDE3_{control['sdn3PlotNumber']}.pdf" if control else "",
        })

    type_decl = (
        "{ unit_name: string; cluster: string; lat: number; lng: number; position_source: string; "
        "bedrooms: string; plot_area_sqm: number; saleable_area_sqm: number; total_area_sqm: number; "
        "original_price_aed: number; unit_type: string; model: string; dcr_url: string; status: string; price: number }[]"
    )
    COORDINATES.write_text(
        "// Generated by scripts/calibrate-lagoons-from-controls.py, then enriched by scripts/enrich-lagoons-map-cards.py.\n"
        "// Coordinates retain direct official controls or calibrated master-plan sources; card fields come from Aldar data.\n"
        f"export const lagoonsVillaCoords: {type_decl} = "
        + json.dumps(rows, indent=2, ensure_ascii=False)
        + ";\n",
        encoding="utf-8",
    )
    print(f"Enriched {len(rows)} Lagoons map-card records")


if __name__ == "__main__":
    main()
